SKIN_NAME = WeatherCloudLive
SKIN_VERSION = 0.1.0

[Extras]
    dashboard_title = WeatherCloud Live
    dashboard_subtitle = Ekran kiosk dla danych live ze stacji

[CheetahGenerator]
    encoding = html_entities

    [[ToDate]]
        [[[live_dashboard]]]
            template = index.html.tmpl

[CopyGenerator]
    copy_once = live.css, live.js

[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
